name: build-and-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Allow Actions to push and write Pages content
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js (with npm cache and public registry)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          registry-url: "https://registry.npmjs.org/"

      - name: Show current npm registry (diagnostic)
        run: |
          echo "npm registry (before):"
          npm config get registry || true
          echo
          echo ".npmrc (if present):"
          if [ -f .npmrc ]; then sed -n '1,200p' .npmrc || true; else echo "<no .npmrc>"; fi

      - name: Ensure public npm registry (extra safety)
        run: |
          echo "Setting npm registry to public npmjs.org"
          npm config set registry https://registry.npmjs.org/
          echo "NPM_CONFIG_REGISTRY=https://registry.npmjs.org/" >> $GITHUB_ENV
          npm config get registry

      - name: Replace Verdaccio host in package-lock.json (CI-only, non-destructive)
        run: |
          if [ -f package-lock.json ]; then
            cp package-lock.json package-lock.json.ci-backup
            if grep -q "verdaccio.verdaccio.svc.cluster.local" package-lock.json; then
              echo "Replacing verdaccio host occurrences with registry.npmjs.org for CI install only."
              perl -0777 -pe 's{https?://verdaccio\.verdaccio\.svc\.cluster\.local:4873}{https://registry.npmjs.org}g' -i package-lock.json
              echo "Replacement done. Showing a sample of replaced lines:"
              grep -n "registry.npmjs.org" package-lock.json | head -n 5 || true
            else
              echo "No Verdaccio references found in package-lock.json."
            fi
          else
            echo "No package-lock.json found; skipping replacement."
          fi

      - name: Configure npm fetch retries & timeouts
        run: |
          npm config set fetch-retries 5
          npm config set fetch-retry-factor 2
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000

      - name: Install dependencies (reliable, with retries)
        env:
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
        run: |
          set -e
          max_retries=3
          attempt=0
          until npm ci --registry=https://registry.npmjs.org/; do
            attempt=$((attempt + 1))
            echo "npm ci failed (attempt $attempt/$max_retries)."
            if [ "$attempt" -ge "$max_retries" ]; then
              echo "Reached max retries. Dumping diagnostics and exiting with failure."
              echo "====== Diagnostics ======"
              echo "npm registry: $(npm config get registry)"
              echo "Top of package.json:"
              head -n 50 package.json || true
              echo "Top of package-lock.json:"
              head -n 50 package-lock.json || true
              echo "====== End diagnostics ======"
              exit 1
            fi
            echo "Waiting 5s before retrying..."
            sleep 5
          done

      - name: Build
        run: npm run build

      - name: Configure git user for deploy commits
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # Use GH_PAGES_PAT secret if present; otherwise fall back to the default token
          github_token: ${{ secrets.GH_PAGES_PAT || secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
